FROM node:8-alpine as build

WORKDIR /app
RUN apk add --no-cache git make gcc g++ python

COPY . .

RUN npm install && npm run build

FROM node:8-alpine

COPY --from=build /app /app

WORKDIR /app
CMD npm run start:api
